"""Add sides to MealOption

Revision ID: 0154274b8f22
Revises: 61d082a8ba77
Create Date: 2025-07-23 10:33:38.234953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0154274b8f22'
down_revision = '61d082a8ba77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sides', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_option', schema=None) as batch_op:
        batch_op.drop_column('sides')

    # ### end Alembic commands ###
