"""Add caterer_id to MealOption

Revision ID: 808c2ffa7fd7
Revises: 0154274b8f22
Create Date: 2025-07-23 10:40:25.994040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808c2ffa7fd7'
down_revision = '0154274b8f22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caterer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['caterer_id'], ['id'])
    # Set a default value for all existing rows (replace 1 with a valid user id if needed)
    op.execute("UPDATE meal_option SET caterer_id = 1")
    with op.batch_alter_table('meal_option', schema=None) as batch_op:
        batch_op.alter_column('caterer_id', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_option', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('caterer_id')

    # ### end Alembic commands ###
