"""Add name to User

Revision ID: b947eaa96e90
Revises: 90cddb57ab67
Create Date: 2025-07-23 10:16:55.157027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b947eaa96e90'
down_revision = '90cddb57ab67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_option', schema=None) as batch_op:
        batch_op.drop_constraint('meal_option_caterer_id_fkey', type_='foreignkey')
        batch_op.drop_column('sides')
        batch_op.drop_column('caterer_id')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'menu', ['menu_id'], ['id'])
        batch_op.drop_column('delivery_address')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_phone_key', type_='unique')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('user_phone_key', ['phone'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_address', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('menu_id')

    with op.batch_alter_table('meal_option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caterer_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('sides', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('meal_option_caterer_id_fkey', 'user', ['caterer_id'], ['id'])

    # ### end Alembic commands ###
